### ISSUE TITLE
Shared subscription don't forward all messages in cluster after restarts

### ISSUE THREAD

**Issue by tinto82** [vernemq/docker-vernemq#133] opened 2019-04-30 15:19 UTC
Hello,
our environments are made up of at least 5 nodes running with Kubernetes on Google Cloud Platform.
We were working with an official docker image "erlio/docker-vernemq:1.7.1", in particular a cluster made up of 3 Pods.
In development environment pods resources limits are 0.1 cpu and 256 Mb RAM for each pod, in other environments 1 cpu and 3 Gb RAM. Every POD has HAProxy in front of container Vernemq.

We have clients using shared subscription to receive messages from all Vernemq nodes. Looking to the diagram we have 3 clients with shared subscription to a service that works like load balancer. So when someone publish in a Vernemq Node, for example Node1, the message can be received also by clients not connected directly to Node1.

![vernemq-cluster](https://user-images.githubusercontent.com/42969153/56969653-e935d900-6b65-11e9-9b10-7db3a7803781.png)

During test phase we noticed that sometimes messages can't be received. In particular this happens after a Vernemq cluster restart (for new deployments for example): during the restart phase Kubernetes restart Node3, that Node2 and in the end Node1. After that with command _"vmq-admin cluster show"_ the cluster looks well formed but can't receive messages published in Node1. In Node1 logs we found this error message:

`FORMAT ERROR: "can't publish to shared subscription ~p due to '~p', msg: Msg" [<<"amqp-mqtt-bridge-expeu">>,no_subscribers {vmq_msg,<<215,126,154,243,62,142,46,105,244,202,50,17,168,180,48,233>>,[<<>>,<<"{svc_id}">>,<<"svc">>,<<"{device_id}">>,<<"device">>,<<"updateStatus">>],<<"{\"body\":"{body}">>,false,false,0,[],false,prefer_local,#{},undefined}]`

After several tests we noticed that after restart clients are connected to Node2 and/or Node3. It looks like messages are forwarded only locally, although in Vernemq config we defined: _**"shared_subscription_policy = prefer_local"**_, seem after restarts nodes acts like _**local_only**_ policy. So if Client1 and Client2 are subscribed in Node2 and Client3 in Node3, when publish a message to Node2 that can be receive by Client1 and Client2; when publish a message to Node1 nobody receive the message.

This seems confirmed to the fact that manually restarting Node2 and Node3 at the same time (so clients after that are connected all to Node1), messages can be received only if publish to Node1.

After that we tried with _**"shared_subscription_policy = random"**_: with than parameter after restart messages can be received by every clients if published in Node2 and Node3, but only by clients directly connected in Node1. In this case logs don't show any errors.

**Comment by ioolkos** [comment] 2019-04-30 15:28
@tinto82 thank you for the effort to document this extensively! 
We'll have to think about this. 
@larshesel @dergraf does this sound familiar? I seem to remember similar issues but we have to think whether the restarting of nodes creates some sort of edge cases for the shared subscriptions, or misses subscriptions or anything like that.

**Comment by dergraf** [comment] 2019-04-30 17:18
just to clarify, your pods are in a statefulset?

**Comment by tinto82** [comment] 2019-05-02 06:47
@dergraf hi, yes, are in statefulset

**Comment by larshesel** [comment] 2019-05-02 12:24
Hi, can you show us the vernemq.conf file - how do the subscribers connect? with clean_session false or true?

**Comment by larshesel** [comment] 2019-05-02 12:50
I've been playing around with this in a local cluster and so far wasn't able to spot any misbehavior. Can you reproduce this in a step-by-step way which I can then try to follow?

**Comment by tinto82** [comment] 2019-05-02 15:16
Hi @larshesel , this is the sequence of action:
- client subscribes with shared subscription; with `vmq-admin session show --node` can see that is connect to the first POS (id 0);
- make a Kubernetes deployment, so:
  1) third POD restarts (id 2): when restarting the discover process take POD id 0 so uses it to join cluster;
  2) second POD restarts (id 1): when restarting the discover process take POD id 0 so uses it to join cluster;
  3) first POD restarts (id 0): when restarting the discover process take POD id 1 so uses it to join cluster;
- now client is connected to POD id 1 or id 2;
- with **"shared_subscription_policy = prefer_local"** when publish a message to POD where client is connected client can get the message, otherwise no message received (and log error like reported initially);
- with **"shared_subscription_policy = random"** when publish a message to POD id 1 or id 2 client can get the message, otherwise no message received (and no log error).

Our clients connect with clean_session true but keep subscribing to the same topic each 2 minutes: this because we had sometimes a problem with lost subscriptions.

How can i send you vernemq.conf privately?

Tell me if we can do something to help your analysis.
Thank you

**Comment by zapotek6** [comment] 2019-05-04 08:11
Hi @larshesel, @dergraf, @ ioolkos, I'm a colleague of @tinto82. We've tried to gather other information

# Shared subscription issue

## Environment

We've a cluster of three nodes:

```sh
% kubectl exec -it vernemq-sts-0 vmq-admin cluster show
Defaulting container name to vernemq-app.
Use 'kubectl describe pod/vernemq-sts-0 -n default' to see all of the containers in this pod.
+----------------------------------------------------+-------+
|                        Node                        |Running|
+----------------------------------------------------+-------+
|VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local| true  |
|VerneMQ@vernemq-sts-1.hub2.default.svc.cluster.local| true  |
|VerneMQ@vernemq-sts-0.hub2.default.svc.cluster.local| true  |
+----------------------------------------------------+-------+
```

```sh
% kubectl exec -it vernemq-sts-1 vmq-admin cluster show
Defaulting container name to vernemq-app.
Use 'kubectl describe pod/vernemq-sts-1 -n default' to see all of the containers in this pod.
+----------------------------------------------------+-------+
|                        Node                        |Running|
+----------------------------------------------------+-------+
|VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local| true  |
|VerneMQ@vernemq-sts-1.hub2.default.svc.cluster.local| true  |
|VerneMQ@vernemq-sts-0.hub2.default.svc.cluster.local| true  |
+----------------------------------------------------+-------+
```

```sh
% kubectl exec -it vernemq-sts-2 vmq-admin cluster show
Defaulting container name to vernemq-app.
Use 'kubectl describe pod/vernemq-sts-2 -n default' to see all of the containers in this pod.
+----------------------------------------------------+-------+
|                        Node                        |Running|
+----------------------------------------------------+-------+
|VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local| true  |
|VerneMQ@vernemq-sts-1.hub2.default.svc.cluster.local| true  |
|VerneMQ@vernemq-sts-0.hub2.default.svc.cluster.local| true  |
+----------------------------------------------------+-------+
```

I've three client, respectively connected to node 0, 1 and 2. All these clients are subscribed to
the topic `$share/shared-tester//maremma`

```txt
|shared-8674665223082153551-|VerneMQ@vernemq-sts-1.hub2.default.svc| $share/shared-tester//maremma |
|shared-5577006791947779410-|VerneMQ@vernemq-sts-0.hub2.default.svc| $share/shared-tester//maremma |
|shared-6129484611666145821-|VerneMQ@vernemq-sts-2.hub2.default.svc| $share/shared-tester//maremma |
```

I've another client that is connected to the node 0. This client is used only to publish message.

All the nodes logging verbosity is set to debug.

## Actual

The *sender* publish _every second_ a message to the topic `/maremma`.

**Only the client connected to the node 0 receive messages.**

*node 0* log's snippet

```txt
07:47:13.308 [debug] transition from offline --> online because of add_session
07:47:13.409 [debug] stop due to disconnect
07:47:13.409 [debug] session normally stopped
07:47:15.709 [debug] 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
07:47:15.887 [debug] transition from offline --> online because of add_session
07:47:15.986 [debug] stop due to disconnect
07:47:15.987 [debug] session normally stopped
07:47:18.197 [debug] transition from offline --> online because of add_session
07:47:18.296 [debug] stop due to disconnect
07:47:18.296 [debug] session normally stopped
07:47:20.787 [debug] transition from offline --> online because of add_session
07:47:20.887 [debug] stop due to disconnect
07:47:20.887 [debug] session normally stopped
07:47:20.892 [debug] started plumtree_metadata_manager exchange with 'VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local' (<0.2411.1>)
07:47:20.989 [debug] completed metadata exchange with 'VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local'. nothing repaired
07:47:23.288 [debug] transition from offline --> online because of add_session
07:47:23.391 [debug] stop due to disconnect
07:47:23.391 [debug] session normally stopped
07:47:25.710 [debug] 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
07:47:25.887 [debug] transition from offline --> online because of add_session
07:47:25.987 [debug] stop due to disconnect
07:47:25.987 [debug] session normally stopped
07:47:28.201 [debug] transition from offline --> online because of add_session
07:47:28.300 [debug] stop due to disconnect
07:47:28.300 [debug] session normally stopped
07:47:30.985 [debug] started plumtree_metadata_manager exchange with 'VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local' (<0.2452.1>)
07:47:30.987 [debug] transition from offline --> online because of add_session
07:47:31.091 [debug] stop due to disconnect
07:47:31.091 [debug] session normally stopped
07:47:31.198 [info] completed metadata exchange with 'VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 1 keys
07:47:33.493 [debug] transition from offline --> online because of add_session
07:47:33.592 [debug] stop due to disconnect
07:47:33.592 [debug] session normally stopped
07:47:34.587 [debug] session normally stopped
07:47:35.711 [debug] 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
07:47:35.891 [debug] transition from offline --> online because of add_session
07:47:35.990 [debug] stop due to disconnect
07:47:35.990 [debug] session normally stopped
07:47:38.208 [debug] transition from offline --> online because of add_session
07:47:40.892 [debug] transition from offline --> online because of add_session
07:47:40.986 [debug] started plumtree_metadata_manager exchange with 'VerneMQ@vernemq-sts-1.hub2.default.svc.cluster.local' (<0.2501.1>)
07:47:40.995 [debug] completed metadata exchange with 'VerneMQ@vernemq-sts-1.hub2.default.svc.cluster.local'. nothing repaired
07:47:41.093 [debug] stop due to disconnect
07:47:41.093 [debug] session normally stopped
07:47:42.396 [debug] stop due to disconnect
07:47:42.396 [debug] session normally stopped
07:47:43.690 [debug] transition from offline --> online because of add_session
07:47:43.889 [debug] stop due to disconnect
07:47:43.889 [debug] session normally stopped
07:47:45.712 [debug] 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
07:47:45.788 [debug] transition from offline --> online because of add_session
07:47:45.887 [debug] stop due to disconnect
07:47:45.888 [debug] session normally stopped
07:47:48.201 [debug] transition from offline --> online because of add_session
07:47:48.301 [debug] stop due to disconnect
07:47:48.302 [debug] session normally stopped
07:47:50.889 [debug] transition from offline --> online because of add_session
07:47:50.987 [debug] started plumtree_metadata_manager exchange with 'VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local' (<0.2545.1>)
07:47:50.992 [debug] stop due to disconnect
07:47:50.992 [debug] session normally stopped
07:47:51.003 [debug] completed metadata exchange with 'VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local'. nothing repaired
07:47:53.494 [debug] transition from offline --> online because of add_session
07:47:53.593 [debug] stop due to disconnect
07:47:53.593 [debug] session normally stopped
07:47:55.713 [debug] 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
07:47:55.793 [debug] transition from offline --> online because of add_session
07:47:55.889 [debug] stop due to disconnect
07:47:55.890 [debug] session normally stopped
07:47:58.199 [debug] transition from offline --> online because of add_session
07:47:58.298 [debug] stop due to disconnect
07:47:58.299 [debug] session normally stopped
07:48:00.986 [debug] transition from offline --> online because of add_session
07:48:00.987 [debug] started plumtree_metadata_manager exchange with 'VerneMQ@vernemq-sts-1.hub2.default.svc.cluster.local' (<0.2589.1>)
07:48:01.040 [info] completed metadata exchange with 'VerneMQ@vernemq-sts-1.hub2.default.svc.cluster.local'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 1 keys
07:48:01.091 [debug] stop due to disconnect
07:48:01.091 [debug] session normally stopped
07:48:03.492 [debug] transition from offline --> online because of add_session
07:48:03.592 [debug] stop due to disconnect
07:48:03.592 [debug] session normally stopped
07:48:04.587 [debug] session normally stopped
07:48:05.714 [debug] 0ms mailbox traversal, schedule next lazy broadcast in 10000ms, the min interval is 10000ms
07:48:05.788 [debug] transition from offline --> online because of add_session
07:48:05.887 [debug] stop due to disconnect
07:48:05.887 [debug] session normally stopped
07:48:08.200 [debug] transition from offline --> online because of add_session
07:48:08.298 [debug] stop due to disconnect
07:48:08.298 [debug] session normally stopped
07:48:10.887 [debug] transition from offline --> online because of add_session
07:48:10.987 [debug] stop due to disconnect
07:48:10.987 [debug] session normally stopped
07:48:10.988 [debug] started plumtree_metadata_manager exchange with 'VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local' (<0.2636.1>)
07:48:11.035 [debug] completed metadata exchange with 'VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local'. nothing repaired
```

lastly we've had a look at the source code and as a pure **speculation** we think that the problem is around the following function

`vmq_reg_trie.erl`

```erl
-spec fold(subscriber_id(), topic(), fun(), any()) -> any().

fold({MP, _} = SubscriberId, Topic, FoldFun, Acc) when is_list(Topic) ->
    fold_(SubscriberId, FoldFun, Acc,
          [{Topic, node()}  %% local subscriptions without wildcard
           |lists:append(
              match(MP, Topic), %% local & remote subscriptions with wildcard
              get_remote_subscribers(MP, Topic)) %% remote subscriptions without wildcards
          ], []).
```

Based on that hypothesis we've gathered the content of the following ETS table on every node

- vmq_trie_subs_fanout
- vmq_trie_subs
- vmq_trie_remote_subs
- vmq_trie_topic
- vmq_trie_node
- vmq_trie

You'll find the ets tables content in the attached file
[node_0_status.txt](https://github.com/vernemq/docker-vernemq/files/3144136/node_0_status.txt)
[node_1_status.txt](https://github.com/vernemq/docker-vernemq/files/3144137/node_1_status.txt)
[node_2_status.txt](https://github.com/vernemq/docker-vernemq/files/3144138/node_2_status.txt)

**Comment by ioolkos** [comment] 2019-05-04 08:39
Thanks for the additional information and material!

@dergraf @larshesel can we approach this by having an actual model (or a mental model) for a 3-node shared subscription situation, reflecting all strategies, and restart/netsplit situations? 
The first question is what we want to happen for all branches/cases, and the second question is whether we find the the branch/reason for the issue at hand.

**Comment by larshesel** [comment] 2019-07-31 08:45
Can you try the experiment with 1.9.0?

**Comment by zapotek6** [comment] 2019-07-31 09:41
> Can you try the experiment with 1.9.0?

Sure. We need time to organize the test and then route few devices to work with that MQTT environment.

We're approaching the vacation period so this test may takes longer than usual.

**Comment by larshesel** [comment] 2019-09-18 05:50
Closing this for now - let us know if more information becomes available.

**Closed by larshesel** 2019-09-18 05:50 UTC
