### ISSUE TITLE
 VerneMQ cluster node restart failed

### ISSUE THREAD

**Issue by onlywangyh** [vernemq/docker-vernemq#81] opened 2018-11-15 09:46 UTC
We create a VMQ cluster in docker . There are two nodes here. The first node is ok，but once the second node is closed, it will not start.
Our steps are as follows：
1、docker run --name vernemq1 -p 0.0.0.0:1183:1883 -p 0.0.0.0:1888:8888 -v /app/vernemq/config/vernemq.conf:/etc/vernemq/vernemq.conf  -d erlio/docker-vernemq（we want all nodes to use the same config file. And the port 8888 is for status page）

2、docker inspect bd71a898d734 | grep \"IPAddress\" （we find the ip and the ip is "172.17.0.2"）

3、docker run -e "DOCKER_VERNEMQ_DISCOVERY_NODE=172.17.0.2" --name vernemq2 -p 0.0.0.0:1283:1883 -p 0.0.0.0:2888:8888 -v /app/vernemq/config/vernemq.conf:/etc/vernemq/vernemq.conf -v /app/vernemq/static:/usr/lib/vernemq/lib/vmq_server-1.6.1/priv/static -d erlio/docker-vernemq

The node vernemq2 is working properly，but the logs shows some error. 

09:40:41.723 [error] Failed to start Ranch listener {{0,0,0,0},8888} in ranch_tcp:listen([{ip,{0,0,0,0}},{port,8888},{nodelay,true},{linger,{true,0}},{send_timeout,30000},{send_timeout_close,true}]) for reason eaddrinuse (address already in use)
09:40:41.723 [error] CRASH REPORT Process <0.432.0> with 0 neighbours exited with reason: {listen_error,{{0,0,0,0},8888},eaddrinuse} in ranch_acceptors_sup:listen_error/4 line 56

If we stop the vernemq2 node,  we can't start it anymore. The error is same as the begin. The only way to 
repair cluster is delete the vernemq2 container node， and build a new one. It's there any way to fix this problems?

**Comment by larshesel** [comment] 2018-11-15 13:03
I'm not sure what the problem is, but you for sure have an issue with the error above. It seems something else is already using port 8888, so either reconfigure that port or stop the process using the port to fix that problem.

After that's fixed it would be interesting to know if any other errors remain.

**Comment by onlywangyh** [comment] 2018-11-16 03:30
Thanks for your help. I think this is not the problems with port. We have further positioned the problem. We fond that if we run a node without the "-e DOCKER_VERNEMQ_DISCOVERY_NODE=172.17.0.2". The node is working properly and can be restarted. But you know if we run the node in docker without the environmental variable, the cluster can't find the new node. So we did the following action：

1、Start a new node "docker run --name vernemq1 -p 0.0.0.0:1183:1883 -p 0.0.0.0:1888:8888 -v /app/vernemq/config/vernemq.conf:/etc/vernemq/vernemq.conf -d erlio/docker-vernemq"

2、Create a new node and join the cluster "docker run -e "DOCKER_VERNEMQ_DISCOVERY_NODE=172.17.0.2" --name vernemq2 -p 0.0.0.0:1283:1883 -p 0.0.0.0:2888:8888 -v /app/vernemq/config/vernemq.conf:/etc/vernemq/vernemq.conf -v /app/vernemq/static:/usr/lib/vernemq/lib/vmq_server-1.6.1/priv/static -d erlio/docker-vernemq" (But there is a problem with this container that can't be restart  )

3、Delete this container and start a new one without  environmental variable.  "docker run  --name vernemq2 -p 0.0.0.0:1283:1883 -p 0.0.0.0:2888:8888 -v /app/vernemq/config/vernemq.conf:/etc/vernemq/vernemq.conf -v /app/vernemq/static:/usr/lib/vernemq/lib/vmq_server-1.6.1/priv/static -d erlio/docker-vernemq" 

The cluster will find the vernemq2 node and the node can be restart. I think when run container  with " -e "DOCKER_VERNEMQ_DISCOVERY_NODE=172.17.0.2" " will be mistake.

So I build node without  environmental variable firstly and try to use vmq-admin add this node to cluster. But it is failed. Error message is "Couldn't join cluster due to not_reachable". This is the reason due to join the cluster approach in different physical machines and containers caused it ？

Then I check the dockerfile and find " CMD ["start_vernemq"] "  .  I enter the container and search for  the "DOCKER_VERNEMQ_DISCOVERY_NODE" in  "start_vernemq". This is the result " if env | grep -q "DOCKER_VERNEMQ_DISCOVERY_NODE"; then
    echo "-eval \"vmq_server_cmd:node_join('VerneMQ@${DOCKER_VERNEMQ_DISCOVERY_NODE}')\"" >> /etc/vernemq/vm.args " 

So this is the way to join a node to a cluster  in containers? I also tried to execute this command with correct ip address " echo "-eval \"vmq_server_cmd:node_join('VerneMQ@172.17.0.2')\"" >> /etc/vernemq/vm.args ". It didn't work, and this node can't restart anymore. So this is a bugs?

**Comment by dergraf** [comment] 2018-11-28 15:13
We can confirm that a bug exist with restarting containers that use the `DOCKER_VERNEMQ_DISCOVERY_NODE` variable.

The current start script is adding an extra `-eval` command to the `vm.args` which is evaluated to join the node with the discovery node. For every restart such an `-eval` command gets added therefore messing up with the auto discovery, resulting in a start failure of the container.

**Comment by dergraf** [comment] 2018-11-28 15:49
@onlywangyh could you please try to reproduce your issue with the fix provided by #88 . Thanks!

**Comment by onlywangyh** [comment] 2018-11-29 16:13
Thanks a lot!

**Comment by dergraf** [comment] 2019-01-07 08:36
Closing this, please feel free to reopen if the bug still exist for you.

**Closed by dergraf** 2019-01-07 08:36 UTC
