### ISSUE TITLE
Uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by Rorschach-10** [vernemq/docker-vernemq#340] opened 2023-01-27 06:23 UTC
Unable to start vernemq with the docker-compose file. 
![image](https://user-images.githubusercontent.com/86289058/215022552-c184104e-1894-4da5-9cb4-a9a8e80e82c5.png)

**Comment by ioolkos** [comment] 2023-01-27 10:54
@Rorschach-10 The Docker packages are not built for AMD64.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by dereulenspiegel** [comment] 2023-02-06 09:49
I am getting the exact same issue on a M1 mac. The problem is not really the segfault here as this is probably only qemu doing the amd64->aarch64 translation crashing because the binary it is translating is crashing.
The problem is this message:
```
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.
  ```

This message happens with the official image with qemu emulation and with the Rosetta based emulation (experimental docker feature). It even happens when I build a custom vernemq image as a native armv8 image.

On x86-64 machines it works fine, only M1 macs seem to be impacted. Unfortunately I currently do not have other aarch64 processors at my disposal to check if this is a general problem with running vernemq on aarch64 or if this is something specifc to docker for mac on M1 processors.

**Comment by codeadict** [comment] 2023-02-06 14:06
I have an ARM fix branch that will open PR this week

**Comment by dereulenspiegel** [comment] 2023-02-06 14:55
@codeadict that's awesome. So if I understand this correctly this needs to be merged into venemq and then this repo needs to release another image with the fix (and probably implement multi arch images)?

I still would have assumed that amd64 images would work with the emulation layer.

**Comment by codeadict** [comment] 2023-02-06 19:43
Correct @dereulenspiegel . The fix will go thru VerneMQ, we need to make a release and then write a multi arch image.

**Closed** 2023-09-18 16:10 UTC
